version: "2"

services:
  jenkins:
    image: jenkins
    ports:
      - "80:8080"
    networks:
      - front-tier
  slave1:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/group:/etc/group
      - /home/${USER}/.docker:/home/jenkins/.docker
    image: otomato/jenkins-slave-alpine:python
    networks:
      - front-tier
      - back-tier
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - back-tier
networks:
  front-tier:
  back-tier:
