version: "2"

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "80:8080"
    networks:
      - front-tier
      - back-tier
  slave1:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: otomato/jenkins-slave-alpine:curl
    networks:
      - front-tier
      - back-tier
networks:
  front-tier:
  back-tier:
